# Generated by Django 4.0.4 on 2023-02-10 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='user_feedback',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
