# Generated by Django 4.0.4 on 2023-02-11 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0002_feedback_user_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='time_feedback',
            field=models.DateTimeField(null=True),
        ),
    ]
