# Generated by Django 4.0.4 on 2023-02-13 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0005_feedback_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='rate',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
    ]
