# Generated by Django 4.0.4 on 2022-11-20 21:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, verbose_name='Категорія')),
                ('slug', models.SlugField(max_length=255, null=True, unique=True, verbose_name='URL')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, null=True, verbose_name='Назва товару')),
                ('slug', models.SlugField(max_length=100, null=True, unique=True)),
                ('photo', models.ImageField(null=True, upload_to='img')),
                ('price', models.FloatField(blank=True, null=True, verbose_name='Ціна товару')),
                ('discount', models.IntegerField(blank=True, null=True, verbose_name='Знижка у %')),
                ('short_description', models.TextField(blank=True, max_length=5000, null=True, verbose_name='Короткий опис')),
                ('description', models.TextField(blank=True, max_length=5000, null=True, verbose_name='Опис')),
                ('details', models.TextField(blank=True, max_length=5000, null=True, verbose_name='Деталі')),
                ('label', models.CharField(blank=True, choices=[('Новинка', 'Новинка'), ('Популярне', 'Популярне')], max_length=20, null=True, verbose_name='Акційна мітка')),
                ('battery', models.CharField(blank=True, choices=[('1000 мАгод', '1000 мАгод'), ('5000 мАгод', '5000 мАгод'), ('10000 мАгод', '10000 мАгод'), ('20000 мАгод', '20000 мАгод')], max_length=20, null=True, verbose_name='Ємність акумуляторної батареї')),
                ('quantity', models.IntegerField(default=1)),
                ('cat', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='store.category')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordered', models.BooleanField(default=False)),
                ('quantity', models.IntegerField(default=1)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.item')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('ordered', models.BooleanField(default=False)),
                ('ordered_date', models.DateTimeField(blank=True)),
                ('items', models.ManyToManyField(to='store.orderitem')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='gallery')),
                ('Item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='store.item')),
            ],
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_favorite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.item')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
