# Generated by Django 4.0.4 on 2022-12-14 21:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_city_adrress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adrress',
            name='address',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='adrress',
            name='ref',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.city'),
        ),
    ]
