# Generated by Django 4.0.4 on 2022-12-16 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_rename_adrress_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='ref',
            new_name='city',
        ),
    ]
