# Generated by Django 4.0.4 on 2022-12-20 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_remove_order_address_np_remove_order_phone_np'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='address_np',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='first_name_np',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='last_name_np',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='phone_np',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
