# Generated by Django 4.0.4 on 2023-02-09 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0023_feedback'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Feedback',
        ),
    ]
