# Generated by Django 4.0.4 on 2022-11-30 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userbase',
            old_name='update',
            new_name='updated',
        ),
        migrations.AddField(
            model_name='userbase',
            name='town_city',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
