# Generated by Django 4.0.4 on 2022-05-21 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_item_description_item_discount_price_item_price_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='discount_price',
            new_name='discount',
        ),
    ]
