# Generated by Django 4.0.4 on 2022-05-21 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_item_label'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='label',
            field=models.CharField(blank=True, choices=[('Новика', 'Новинка'), ('Популярне', 'Популярне')], max_length=20, null=True),
        ),
    ]
