# Generated by Django 4.0.4 on 2022-06-01 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_category_item_cat'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='slug',
            field=models.SlugField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='description',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='Опис'),
        ),
        migrations.AlterField(
            model_name='item',
            name='discount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='Знижка у %'),
        ),
        migrations.AlterField(
            model_name='item',
            name='label',
            field=models.CharField(blank=True, choices=[('Новика', 'Новинка'), ('Популярне', 'Популярне')], max_length=20, null=True, verbose_name='Акційна мітка'),
        ),
        migrations.AlterField(
            model_name='item',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='Ціна товару'),
        ),
        migrations.AlterField(
            model_name='item',
            name='title',
            field=models.CharField(max_length=100, null=True, verbose_name='Назва товару'),
        ),
    ]
