# Generated by Django 4.0.4 on 2022-12-16 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_alter_adrress_address_alter_adrress_ref'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Adrress',
            new_name='Address',
        ),
    ]
