# Generated by Django 4.0.4 on 2022-06-01 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_item_slug_alter_item_description_alter_item_discount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='slug',
            field=models.SlugField(max_length=100, null=True, unique=True),
        ),
    ]
