# Generated by Django 4.0.4 on 2022-12-17 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_rename_ref_address_city'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Address',
        ),
    ]
