# Generated by Django 4.0.4 on 2022-06-12 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_alter_item_photo_gallery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='label',
            field=models.CharField(blank=True, choices=[('Новика', 'Новинка'), ('popular', 'Популярне')], max_length=20, null=True, verbose_name='Акційна мітка'),
        ),
    ]
