# Generated by Django 4.0.4 on 2022-06-17 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_alter_item_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='battery',
            field=models.CharField(blank=True, choices=[('1000 мАгод', '1000 мАгод'), ('5000 мАгод', '5000 мАгод'), ('10000 мАгод', '10000 мАгод'), ('20000 мАгод', '20000 мАгод')], max_length=20, null=True, verbose_name='Ємність акумуляторної батареї'),
        ),
    ]
