# Generated by Django 4.0.4 on 2022-12-29 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0019_order_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='item_total',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
