# Generated by Django 4.0.4 on 2023-01-03 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0021_remove_order_total_remove_orderitem_item_total'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Battery',
        ),
    ]
