# Generated by Django 4.0.4 on 2022-08-28 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0021_shippingaddress_email_shippingaddress_first_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='ordered_date',
            field=models.DateTimeField(blank=True),
        ),
    ]
