# Generated by Django 4.0.4 on 2022-09-12 18:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0022_alter_order_ordered_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='label',
            field=models.CharField(blank=True, choices=[('Новинка', 'Новинка'), ('Популярне', 'Популярне')], max_length=20, null=True, verbose_name='Акційна мітка'),
        ),
        migrations.CreateModel(
            name='Faforite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.item')),
            ],
        ),
    ]
