# Generated by Django 4.0.4 on 2022-09-12 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0022_alter_order_ordered_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='label',
            field=models.CharField(blank=True, choices=[('Новинка', 'Новинка'), ('Популярне', 'Популярне')], max_length=20, null=True, verbose_name='Акційна мітка'),
        ),
    ]
