# Generated by Django 4.0.4 on 2022-10-26 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0031_remove_order_customer_order_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='short_description',
            field=models.TextField(blank=True, max_length=5000, null=True, verbose_name='Короткий опис'),
        ),
    ]
