# Generated by Django 4.0.4 on 2022-11-16 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0034_alter_item_discount_alter_item_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='discount',
            field=models.IntegerField(blank=True, null=True, verbose_name='Знижка у %'),
        ),
    ]
