# Generated by Django 4.0.4 on 2022-12-05 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_rename_update_userbase_updated_userbase_town_city'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userbase',
            options={},
        ),
        migrations.AlterField(
            model_name='userbase',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='Електронна адреса'),
        ),
    ]
